Hi-Transcendence/ft_transcendence

front/client/src/Content.css
front/client/src/Content.tsx
front/client/src/Nav.css
front/client/src/Nav.tsx
front/client/src/Side.css
front/client/src/Side.tsx
front/client/src/index.tsx

- 랭킹 페이지에 필요한 레이아웃(Nav, Side, 랭킹과 프로필 등의 내용물을 담을 Content) 작성
- Nav 컴포넌트, css 작성
- Side 컴포넌트, css 작성
- Content 컴포넌트, css 작성
- 작성한 컴포넌트 모아서 index페이지에서 render

[Feat - Front] / 랭킹페이지 레이아웃 작성 #4

---

front/client/src/Rank.tsx

- RankTable에서 데이터를 받아오도록 변경, api 랭킹번호 받아오도록 변경
- Rank컴포넌트에 있던 get 부분을 RankTable에서 요청하는 것으로 변경
- 받아오는 api의 타입(userRank)에 rank(랭킹번호) 추가.
- 타입 userRank에 winRate를 원래는 소수점 number를 받아오는 것에서 50%와 같이 스트링으로 받도록 변경.

[Fix - Front] 랭킹 페이지 리팩토링 #11

---

back/server/src/app.module.ts

- ormconfig 수정 
- 데이터베이스 정보를 통일시키기 위해 ormconfig를 수정

[fix - back] ormconfg 수정 #17

---

back/server/src/channel/channel.controller.spec.ts
back/server/src/channel/channel.controller.ts
back/server/src/channel/channel.module.ts
back/server/src/channel/channel.service.spec.ts
back/server/src/channel/channel.service.ts
back/server/src/channel/dto/create-channel.dto.ts
back/server/src/channel/dto/update-channel.dto.ts
back/server/src/channel/entities/channel.entity.ts

- Feat-Back/channel모듈생성
-  Feat-Back/channel모듈생성

Feat-Back/channel모듈생성#21

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/mypage/FriendList.tsx
front/client/src/components/mypage/MatchList.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/pages/MyPage.tsx
front/client/src/styles/mypage/FriendList.css
front/client/src/styles/mypage/MatchList.css
front/client/src/styles/mypage/MyPage.css
front/client/src/styles/mypage/UserInfo.css

- 마이페이지 컴포넌트 및 css 작성
- MyPage 컴포넌트 : 아래 컴포넌트 3개를 배치하고 띄우는 용도
- UserInfo 컴포넌트 : 유저 정보 및 변경 버튼에 대한 컴포넌트.
- MatchList 컴포넌트 : 대전기록 리스트에 대한 컴포넌트.
- FriendList 컴포넌트 : 친구목록 리스트에 대한 컴포넌트.

[Feat - Front] 마이페이지 만들기 #18

---

front/client/src/components/mypage/FriendList.tsx
front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchList.tsx
front/client/src/components/mypage/MatchTable.tsx
front/client/src/styles/mypage/FriendTable.css
front/client/src/styles/mypage/MatchTable.css

- 대전기록, 친구목록 컴포넌트 추가.
- 대전기록, 친구목록 컴포넌트를 만들고 더미데이터로 띄우고 있음.

[Feat - Front] 대전기록, 친구목록 테이블 추가 #28

---

front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchTable.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/types/MyPageTypes.tsx

- 마이페이지 컴포넌트들 더미데이터 -> 서버에서 데이터 받아오도록 추가.
- UserInfo, MatchTable, FriendTable 더미데이터를 get 사용하도록 교체
- 각각에 대한 타입 만들기. userInfo, matchList, friendList 타입 추가됨.

[fix - Front/Back] 마이페이지 컴포넌트들 get요청으로 수정 #30

---

back/server/src/app.module.ts
back/server/src/stats/dto/res-rank.dto.ts
back/server/src/stats/dto/res-stat.dto.ts
back/server/src/stats/entities/stat.entity.ts
back/server/src/stats/stats.controller.ts
back/server/src/stats/stats.service.ts
back/server/src/users/dto/create-user.dto.ts
back/server/src/users/dto/res-user-mypage.dto.ts
back/server/src/users/dto/update-user.dto.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.controller.spec.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.module.ts
back/server/src/users/users.service.spec.ts
back/server/src/users/users.service.ts

- /users/:id/mypage url을 통해 특정 유저 정보 GET api 구현
- user 데이터베이스와 stat 데이터베이스 관계 생성
- 관계를 통해 stat에서 user의 닉네임 가져옴
- 또한 user에서 stat정보 가져옴
- avatar, channel_id 은 미구현

[Feat - Back] 특정 유저 정보 GET api 구현 #23

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/lobby/ChannelList.tsx
front/client/src/pages/Lobby.tsx
front/client/src/styles/Lobby/ChannelList.css
front/client/src/styles/Lobby/Lobby.css

- 로비 페이지 틀 만들기
- Lobby 컴포넌트, ChannelList 컴포넌트 만들어놓음. 추후 더미데이터를 서버 데이터로 교체하는 작업 필요

[Feat - Front] 로비 페이지 만들기 #33

---

back/server/src/app.module.ts
back/server/src/database/database.module.ts
back/server/src/database/database.providers.ts
back/server/src/match/dto/create-match.dto.ts
back/server/src/match/dto/update-match.dto.ts
back/server/src/match/entities/match.entity.ts
back/server/src/match/match.controller.spec.ts
back/server/src/match/match.controller.ts
back/server/src/match/match.module.ts
back/server/src/match/match.providers.ts
back/server/src/match/match.service.spec.ts
back/server/src/match/match.service.ts
back/server/src/stats/stats.module.ts
back/server/src/stats/stats.providers.ts
back/server/src/stats/stats.service.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.module.ts
back/server/src/users/users.providers.ts
back/server/src/users/users.service.ts

- DataSource 생성 및 각 모듈 provider 생성
- database 모듈을 통해 datasource 객체 생성
- stats, users, match 모듈 데이터베이스 모듈과 연결

[Refactor - Back] DataSource 생성 및 각 모듈 레포지토리 생성

---

front/client/src/components/lobby/ChannelList.tsx
front/client/src/components/lobby/ChannelListRow.tsx
front/client/src/styles/Lobby/ChannelList.css
front/client/src/types/LobbyTypes.tsx

- 로비 페이지 더미데이터->get으로 변경, ChannelListRow 컴포넌트 파일로 분리하기
- 로비 페이지 더미데이터에서 get 받아오도록 변경
- ChannelListRow 컴포넌트 파일로 분리

[fix-front] 로비페이지 get으로 수정

---

back/server/src/app.module.ts
back/server/src/database/database.providers.ts
back/server/src/match/dto/res-match.dto.ts
back/server/src/match/entities/match.entity.ts
back/server/src/match/match.controller.ts
back/server/src/match/match.module.ts
back/server/src/match/match.service.ts
back/server/src/stats/entities/stat.entity.ts
back/server/src/stats/stats.module.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.module.ts
back/server/src/users/users.service.ts

- 대전기록 get api 구현
- GET /match/:id api 구현
- 일부 코드 리팩토링

[Feat - Back] 대전기록 Get api 구현 #23

---

front/client/package-lock.json
front/client/package.json
front/client/src/App.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/modal/AvatarChangeModal.tsx
front/client/src/components/modal/Modal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/index.tsx
front/client/src/styles/modal/Modal.css
front/client/src/utils/recoil/modalState.tsx
front/client/yarn.lock

- 모달창 구현. recoil로 활성상태/비활성상태에 따라 나타나도록 구현
- Modal 컴포넌트 작성
- Modal 컴포넌트 하위 컴포넌트로 AvatarChangeModal, NickChangeModal 컴포넌트 추가
- 모달 하나만 호출하고 싶은데 동시에 호출되는 문제 있음 -> 이 부분은 논의해서 다시 설계하고 짜보려 함
- side 컴포넌트에서 socket.io 테스트 코드가 있음 중요하진 않지만 소켓 연결 성공한 코드라 남겨두었음

[Feat- Front] 마이페이지 모달창 구현 #40

---

front/client/src/App.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/modal/Modal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/utils/recoil/modalState.tsx

- main 페이지 Lobby로 이동
- 모든 path앞에 '/'추가

[Fix - Front] main 페이지 수정

---

front/client/src/components/layout/Side.tsx
front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchTable.tsx

- 마이페이지 matchTable, friendTable에 대해 api 주소 수정됨
- 기존의 /users/:id/match 부분을 /match/:id로 수정
- 기존의 /users/:id/friends 부분을 /friend/:id로 수정

[Fix - Front] api 주소 수정

---

front/client/src/components/layout/Side.tsx
front/client/src/components/modal/AvatarChangeModal.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/components/modal/Modal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchTable.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/pages/Lobby.tsx
front/client/src/utils/recoil/modalState.tsx

- Modal 컴포넌트 및 하위 컴포넌트들 리팩토링. 모달이 각자 따로 동작하도록 고침.
- Modal 컴포넌트는 하위 컴포넌트만 포함하도록 변경.
- AvatarChangeModal, NickChangeModal 상태 추가 및 관리
- 로비의 게임 시작 모달 GameStartModal 추가

[Fix - Front] 모달 각자 상태관리 되도록 리팩토링 #45

---

front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchTable.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/types/MyPageTypes.tsx
front/client/src/utils/recoil/dummy.tsx
front/client/src/utils/recoil/modalState.tsx

- 변경된 일부 api 수정, 더미데이터를 dummy.tsx에 정리
- api 수정사항 반영(playerScore1 -> score1 등)
- 더미데이터 utils폴더에 dummy.tsx로 정리

[Fix - Front] 변경된 api에 맞춰 타입 수정

---

front/client/src/App.tsx
front/client/src/components/game/GameModule.tsx
front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchTable.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/pages/Game.tsx
front/client/src/styles/game/Game.css
front/client/src/utils/dummy.tsx

- Game페이지, GameModule 컴포넌트 만들기
- 플레이어 정보와 게임 모듈 컴포넌트가 있는 Game 컴포넌트 만들기. 우선 더미데이터 사용
- 게임을 캔버스에 그려주는 GameModule 컴포넌트 만들기.

[Feat - Front] 게임 페이지 만들기 #49

---

front/client/src/App.tsx
front/client/src/components/lobby/ChannelList.tsx
front/client/src/components/lobby/ChannelListRow.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/pages/Game.tsx
front/client/src/utils/dummy.tsx

- 로비에서 채널 눌렀을 때 게임방으로 이동하도록 구현
- route 개선해서 game/:채널아이디로 이동하게 변경
- post 채널 목록 추가(게임등록 버튼 눌렀을 때 요청 보내도록)
- Game페이지 더미데이터에서 get요청으로 변경

[Feat - Front]채널목록에서 게임방으로 이동

---

front/client/src/components/layout/ChatList.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/styles/layout/Side.css
front/client/src/utils/dummy.tsx
front/client/src/utils/recoil/modalState.tsx

- 유저리스트, 채팅창, 유저프로필 모달 구현
- UserList 컴포넌트 추가
- ChatList 컴포넌트 추가
- 유저를 눌렀을 때 나오는 모달창 구현(get요청 구현해야함)

[Feat - Front] 유저리스트와 채팅 컴포넌트 만들기 #53

---

back/server/src/app.module.ts
back/server/src/channel/channel.controller.ts
back/server/src/channel/channel.module.ts
back/server/src/channel/channel.providers.ts
back/server/src/channel/channel.service.ts
back/server/src/channel/dto/create-channel.dto.ts
back/server/src/channel/dto/get-channelList.dto.ts
back/server/src/channel/dto/post-channel.dto.ts
back/server/src/channel/dto/update-channel.dto.ts
back/server/src/channel/entities/channel.entity.ts
back/server/src/match/match.module.ts
back/server/src/match/match.service.ts
back/server/src/stats/stats.service.ts

- channel api구현
- 로비에서 채널목록 불러오기
- 시작하기 버튼눌렀을시 채널 생성 (임시 구현)

Feat-Back/channel관련api구현

---

back/server/package-lock.json
back/server/package.json
back/server/src/app.module.ts
back/server/src/common/multer.ts
back/server/src/friend/dto/create-friend.dto.ts
back/server/src/friend/dto/res-friend.dto.ts
back/server/src/friend/dto/update-friend.dto.ts
back/server/src/friend/entities/friend.entity.ts
back/server/src/friend/friend.controller.spec.ts
back/server/src/friend/friend.controller.ts
back/server/src/friend/friend.module.ts
back/server/src/friend/friend.providers.ts
back/server/src/friend/friend.service.spec.ts
back/server/src/friend/friend.service.ts
back/server/src/main.ts
back/server/src/match/match.controller.ts
back/server/src/match/match.service.ts
back/server/src/stats/stats.controller.ts
back/server/src/users/dto/res-user-mypage.dto.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.service.ts

- 친구목록 GET 및 이미지 POST, GET api 구현
- 친구목록 GET api 를 포함한 모듈 구현
- multer를 이용하여 이미지 POST api 구현
- static 파일을 통한 이미지 GET 구현

[Feat - back] / 친구목록 GET, 이미지 POST, GET 구현#23

---

back/server/src/channel/channel.controller.ts
back/server/src/channel/channel.service.ts
back/server/src/channel/dto/post-channel.dto.ts

- channel비밀번호변경api구현
- channel비밀번호변경api구현

[Feat-Back] channel비밀번호변경api구현#56

---

back/server/package-lock.json
back/server/package.json
back/server/src/common/multer.ts
back/server/src/friend/dto/create-friend.dto.ts
back/server/src/friend/friend.service.ts
back/server/src/main.ts
back/server/src/match/dto/create-match.dto.ts
back/server/src/match/match.service.ts
back/server/src/stats/dto/create-stat.dto.ts
back/server/src/stats/stats.controller.ts
back/server/src/stats/stats.service.ts
back/server/src/users/dto/create-user.dto.ts
back/server/src/users/dto/res-user-mypage.dto.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.service.ts

- 각 모듈의 유효성 검사 구현
- 존재하지 않은 user에 대한 요청 예외 처리
- 각 input에 대한 유효성 처리
- intraId나 nickname에 대한 유효성 처리는 로그인 페이지 구현 이후 예정

[Feat - Back] 각 모듈의 input에 대한 유효성 검사 구현#62

---

front/client/src/components/layout/Side.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/components/modal/ModalProvider.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/styles/layout/Side.css
front/client/src/types/modalTypes.ts

- Side(유저리스트, 채팅창) 스크롤 구현
- css에 overflow-y 를 적용하여 스크롤 추가

[Feat - Front] side 스크롤 구현 #69

---

front/client/src/components/lobby/ChannelList.tsx
front/client/src/components/modal/AvatarChangeModal.tsx
front/client/src/components/modal/ModalProvider.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/mypage/FriendTable.tsx
front/client/src/components/mypage/MatchTable.tsx
front/client/src/components/mypage/UserInfo.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/pages/Game.tsx
front/client/src/types/LobbyTypes.ts
front/client/src/utils/dummy.ts

- 프로필 사진, 닉네임 변경 등 Post처리 시 문제 해결
- useEffect를 사용하여 랜더링 처리

[Fix - Front] Post 요청 처리 #72

---

back/server/src/channel/channel.controller.ts
back/server/src/channel/channel.service.ts
back/server/src/channel/dto/post-channel.dto.ts

- Feat-Back/channel관전자입장시현재인원수증가시켜주기
- updateCurNumUser 컨트롤러  서비스 구현
- dto 타입 정리

Feat-Back/channel관전자입장시현재인원수증가시켜주기

---

back/server/src/app.module.ts
back/server/src/ban/ban.controller.spec.ts
back/server/src/ban/ban.controller.ts
back/server/src/ban/ban.module.ts
back/server/src/ban/ban.providers.ts
back/server/src/ban/ban.service.spec.ts
back/server/src/ban/ban.service.ts
back/server/src/ban/dto/create-ban.dto.ts
back/server/src/ban/dto/res-ban.dto.ts
back/server/src/ban/dto/update-ban.dto.ts
back/server/src/ban/entities/ban.entity.ts
back/server/src/friend/dto/create-friend.dto.ts
back/server/src/friend/dto/delete-friend.dto.ts
back/server/src/friend/dto/res-friend.dto.ts
back/server/src/friend/entities/friend.entity.ts
back/server/src/friend/friend.controller.ts
back/server/src/friend/friend.service.ts
back/server/src/match/dto/create-match.dto.ts
back/server/src/match/match.controller.ts
back/server/src/match/match.module.ts
back/server/src/match/match.service.ts
back/server/src/stats/stats.controller.ts
back/server/src/stats/stats.module.ts
back/server/src/stats/stats.service.ts
back/server/src/users/dto/res-user-modal.dto.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.module.ts
back/server/src/users/users.service.ts

- 친구목록, 차단목록 및 유저 모달창 api 구현 
- 친구목록 GET POST api 구현
- 차단목록 GET POST api 구현
- 일부 코드 리팩토링
- 유저 모달창에 필요한 GET api 구현

[Feat - Back] 친구목록, 차단목록 및 유저 모달창 api 구현 #62#67#75

---

back/server/package-lock.json
back/server/package.json
back/server/src/app.module.ts
back/server/src/channel/dto/get-channelList.dto.ts
back/server/src/game/game.gateway.ts
back/server/src/game/game.module.ts
back/server/src/game/game.service.ts
back/server/src/game/game.ts

- 게임 기능을 구현했습니다.
- 게임 시작 버튼 클릭 시 카운트 다운 후 게임 기능 구현.
- 게임 시작 시 로비에서 진행중인 게임 리스트 확인 및 관전 참여 기능 구현.
- 게임 도중 비밀번호 변경 기능 구현.
- 게임 도중 ping 확인 기능 구현.
- game.gateway.ts 파일에 소켓 요청을 받는 코드가 있습니다.
- game.service.ts 파일에 소켓 요청에 대한 동작을 구현한 코드가 있습니다.
- game.ts 파일에 게임방 데이터를 보관하고, 게임방 데이터 업데이트에 사용되는 game 클래스의 내용이 있습니다.

Feat back/게임기능구현

---

front/client/src/components/layout/Nav.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/rank/RankRow.tsx
front/client/src/components/users/FriendTable.tsx
front/client/src/pages/Users.tsx
front/client/src/styles/Lobby/Lobby.css
front/client/src/styles/layout/Nav.css

- 싱글 페이지 처리
- a href 를 Link to 로 수정
- Route 에서 path 와 API 비교 수정
- useLocation 사용하여 url변경 시 처리

[Fix - Front] 싱글페이지 처리 #83

---

back/server/src/auth/auth.module.ts
back/server/src/ban/ban.module.ts
back/server/src/friend/friend.module.ts
back/server/src/match/match.module.ts
back/server/src/stats/stats.module.ts
back/server/src/users/users.module.ts

각 모듈간에 다른 모듈의 Service 사용이 필요할 때 직접 해당 Service를 Import 하는 것을
해당 Service의 모듈을 Import하는 것으로 수정했습니다.
(각 모듈의 의존성을 낮추고 Service의 캡슐화를 위해.)
**추가적으로 _vscode의 저장 시 js-prettier 자동 적용 기능_ 사용을 부탁드립니다.
(코드 포맷 통일을 위해)**

[Fix - Back] 모듈 간의 Service 직접 import 수정

---

back/server/src/database/database.providers.ts

- TypeORM 모듈을 생성할 때 DB정보 (DB이름, 비밀번호 등..)가 코드에 그대로 노출되어 있어
.env파일에서 해당 정보들을 가져와서 사용하도록 변경.

[Fix - Back] TypeORM 모듈 설정 환경변수 적용

---

front/client/src/components/game/GameModule.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/components/modal/PasswordSubmitModal.tsx
front/client/src/components/modal/RadioOption.tsx
front/client/src/components/rank/RankRow.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/components/rank/RankTitleRow.tsx
front/client/src/pages/Game.tsx
front/client/src/styles/rank/Rank.css

- 게임 관련 컴포넌트들 보기 쉽게 리팩토링, 게임 기능 업그레이드(렌더링 속도, 반응형)
- 랭킹 타이틀 컴포넌트 분리
- PasswordSubmitModal 삼항연산자로 리턴
- GameStartModal 삼항연산자로 리턴
- GameModule 리팩토링, 캔버스 렌더링 속도 개선
- GameModule 브라우저 크기가 달라져도 유연하게 동작하도록 개선

[Fix - Front] 게임 컴포넌트 리팩토링 #91

---

back/server/.gitignore
back/server/package-lock.json
back/server/package.json
back/server/src/app.module.ts
back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.module.ts
back/server/src/auth/auth.service.ts
back/server/src/database/database.providers.ts
back/server/src/users/entities/user.entity.ts

- 2차인증을 위한 이메일 인증 시스템을 구현하였습니다.
- bcrypt 모듈을 이용하여 해시코드를 생성.
- 만들어진 해시코드를 mailer 모듈을 이용하여 이메일로 전송.
- 사용자의 입력과 해시코드가 동일하다면 유저 DB에 2차인증 여부 수정.

[Feat - Back] 해쉬코드 생성 후 이메일 전송

---

front/client/src/App.tsx
front/client/src/components/LoginChecker.tsx
front/client/src/components/game/GameModule.tsx
front/client/src/components/layout/ChatList.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/lobby/ChannelList.tsx
front/client/src/components/lobby/ChannelListRow.tsx
front/client/src/components/modal/ChannelSettingModal.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/PasswordSubmitModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/styles/layout/Side.css
front/client/src/types/chatTypes.ts
front/client/src/utils/recoil/chatScroll.ts

- 채팅 메시지 서버와 주고 받기 #92 
- 채팅 자동 스크롤 구현 #92
- socket 통신을 사용하여 채팅 메시지 주고 받기
- scroll 기능을 사용하여 채팅창 자동 스크롤 처리

[Feat - Front] 채팅 자동 스크롤 구현 #92

---

back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.service.ts
back/server/src/users/dto/res-user-navi.dto.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.service.ts

- 2차인증 관련 API 요청을 받을 시  클라이언트에게 반환하는 데이터를 수정하였습니다.

[Fix - Back] 2차인증 API Response 데이터 수정

---

back/server/src/app.module.ts
back/server/src/auth/auth.module.ts
back/server/src/auth/auth.service.ts
back/server/src/ban/ban.module.ts
back/server/src/ban/ban.service.ts
back/server/src/chat/chat.module.ts
back/server/src/chat/chat.service.ts
back/server/src/friend/friend.module.ts
back/server/src/friend/friend.service.ts
back/server/src/match/match.module.ts
back/server/src/match/match.service.ts
back/server/src/stats/stats.module.ts
back/server/src/stats/stats.service.ts
back/server/src/users/users.module.ts
back/server/src/users/users.service.ts

- Typeorm 모듈 리팩토링
-  Database 모듈을 제거하고 appmodule에서 바로 import하게 변경

[Refact - Back] Typeorm 모듈 리팩토링

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/pages/SecondAuth.tsx
front/client/src/styles/login/SecondAuth.css
front/client/src/types/myDataTypes.ts
front/client/src/utils/axios.ts
front/client/src/utils/recoil/myData.ts

- 2차 인증 페이지 추가
- 2차인증페이지에 대한 컴포넌트 구현
- 이메일 발송, 코드 발송에 대한 각 메소드 구현
- 2차인증 여부에 따라 렌더링 달라지도록 구현

[Feat - Front] 2차 인증 페이지 추가

---

front/client/src/components/layout/ChatList.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/styles/layout/Side.css
front/client/src/utils/recoil/chat.ts

[Feat - Front] DM 구현 #92

---

front/client/src/components/modal/ProfileModal.tsx

[Feat - Front] 방장기능구현 #104

---

front/client/src/components/layout/UserList.tsx
front/client/src/pages/Game.tsx

- 방장 관련 권한 추가
- 유저리스트에 왕관모양 띄우기
- 채널 설정 버튼 방장만 보이게 하기

[Feat - Front] 유저 리스트, 채널설정버튼에 방장 관련 권한 추가

---

front/client/.gitignore
front/client/src/App.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/modal/LogoutModal.tsx
front/client/src/pages/Login.tsx
front/client/src/types/userTypes.ts
front/client/src/utils/axios.ts

- 게임 매칭 시 오류 해결 
- 로그인 전후 소켓 연결 오류 처리
- App파일에서 route 경로 수정 (game=>channel)
- socket을 연결이 되지 않았을 때 재연결 해주는 코드 추가

[Fix - F/B] 게임 매칭 시 문제 처리 및 소켓 처리 #108 #114

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/styles/modal/Modal.css
front/client/src/styles/users/UserInfo.css

- 2차인증 렌더링 문제, CSS 일부 개선
- 2차인증 완료하고도 메인에서 짧게 2차인증 페이지가 렌더링되던 현상 로딩중입니다 뜨도록 수정
- 모달 버튼, Nav에서 랭킹이 왼쪽에 뜨는 등 CSS 관련 일부 수정

[Fix - Front] 2차인증 렌더링 및 CSS 수정 #108

---

front/client/src/components/layout/Nav.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/types/GameTypes.ts
front/client/src/utils/recoil/gameState.ts

- 게임방 퇴장 시 소켓 join-channel 이벤트 서버로 발송
- 게임방 나갈 시 서버로 join-channel 이벤트 서버로 발송
- 게임방 나갈 시 프론트의 channelState 상태 초기화

[Fix -Front] 게임방 퇴장 시 join-channel이벤트 소켓 emit 추가

---

back/server/src/auth/auth.service.ts
back/server/src/chat/chat.gateway.ts
back/server/src/chat/chat.module.ts
back/server/src/chat/chat.service.ts
back/server/src/chat/chat.ts
back/server/src/game/game.gateway.ts
back/server/src/game/game.module.ts
back/server/src/game/game.service.ts
back/server/src/users/dto/res-user-modal.dto.ts
back/server/src/users/dto/res-user-navi.dto.ts
back/server/src/users/users.module.ts
back/server/src/users/users.service.ts

-  채널 이동 및 채널 방장 기능 구현
-  채널 이동시 채팅방 이동 구현
-  채널 방장 정보 추가
-  방장 기능인 음소거 구현

[Feat - Back] 채널 이동 및 채널 방장 구현 #90

---

front/client/src/components/layout/Nav.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/users/FriendTable.tsx
front/client/src/pages/Login.tsx
front/client/src/utils/recoil/friend.ts

- 친구 리스트 실시간 처리
- axios를 socket으로 변경, 소켓 시작 종료를 서버에 알려주는 방식으로 구현

[Feat - Front] 친구 리스트 실시간 처리 #111

---

back/server/src/chat/chat.gateway.ts
back/server/src/chat/chat.module.ts
back/server/src/chat/chat.service.ts
back/server/src/friend/friend.controller.ts
back/server/src/friend/friend.module.ts
back/server/src/friend/friend.service.ts

-  실시간 친구목록 구현
-  소켓을 통한 실시간 친구목록 업데이트 기능 구현

[Fix - Back] 실시간 친구목록 구현 #119

---

back/server/package-lock.json
back/server/src/app.module.ts
back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.guard.ts
back/server/src/auth/auth.service.ts
back/server/src/ban/ban.service.ts
back/server/src/channel/channel.controller.ts
back/server/src/game/game-manager.ts
back/server/src/game/game.gateway.ts
back/server/src/game/game.module.ts
back/server/src/game/game.service.ts
back/server/src/game/game.ts
back/server/src/game/match-manager.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.service.ts
front/client/src/components/game/GameModule.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/lobby/ChannelListRow.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/components/modal/InviteAcceptModal.tsx
front/client/src/components/modal/ModalProvider.tsx
front/client/src/components/modal/PasswordSubmitModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/pages/Game.tsx
front/client/src/pages/Login.tsx
front/client/src/styles/game/Game.css
front/client/src/styles/modal/Modal.css

- 게임 모듈 리팩토링 및 업데이트
- 백엔드 : 게임 모듈 리팩토링, 새로고침 시 게임 재개, 게임방 삭제 기능 업데이트
- 프론트엔드 : 매칭 취소, 나가기 기능, 배경 이미지 바꿀 수 있도록 리팩토링 등 업데이트

[Feat - FE, BE] 게임 모듈 리팩토링 및 업데이트

---

front/client/src/App.tsx
front/client/src/components/ErrorChecker.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/modal/AvatarChangeModal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/components/users/MatchTable.tsx
front/client/src/pages/Error.tsx
front/client/src/pages/Error404.tsx
front/client/src/pages/SecondAuth.tsx
front/client/src/pages/Users.tsx
front/client/src/styles/error/error.module.css
front/client/src/utils/recoil/error.ts

- 에러 페이지 구현
- 각종 동작 오류 시 alert창 추가
- 요청 에러 발생 시 errorpage이동

[Feat - Front] 에러 페이지 #124

---

back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.service.ts
back/server/src/ban/ban.controller.ts
back/server/src/ban/ban.service.ts
back/server/src/ban/entities/ban.entity.ts
back/server/src/common/multer.ts
back/server/src/friend/dto/res-friend.dto.ts
back/server/src/friend/friend.service.ts
back/server/src/stats/stats.service.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.service.ts

- 에러처리 코드 수정
- db에서 해당 닉네임 유저 못찾을 시 에러 처리
- 이미 존재하는 닉네임 에러 처리
- 파일 용량 및 확장자 에러 처리
- 이미 친구 상태, 차단 상태인 경우 에러 처리

[Fix - Back] 에러처리 코드 수정 #126

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/pages/Error.tsx

- 프로필 페이지에서 다른 프로필 페이지로 이동할 때 친구 리스트 깜빡임 처리 
- 최초 로그인 및 첫 유저일 경우 친구 리스트가 출력되지 않는 문제 해결

[Fix - Front] 친구 리스트 깜빡임 처리 #130

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/pages/Game.tsx
front/client/src/utils/recoil/chat.ts

- 채널 이동 시 채팅창 초기화
- chatList의 useState 를 useRecoilState로 바꿔 채널 이동 시 초기화 시키는 부분 추가

[Fix - Front] 채널 이동 시 채팅 초기화

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/modal/AvatarChangeModal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/components/users/MatchTable.tsx
front/client/src/pages/Error.tsx
front/client/src/pages/SecondAuth.tsx
front/client/src/pages/Users.tsx

- 서버가 종료되었을 때 로그아웃 시키고 로그인 페이지로 이동시키는 에러페이지 추가

[Feat - Front] 서버 에러페이지 추가

---

front/client/src/components/layout/Layout.tsx
front/client/src/components/modal/AvatarChangeModal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/pages/Game.tsx
front/client/src/pages/SecondAuth.tsx

- 유효성 검사 및 window.location.replace 제거
- 이메일에 대한 유효성검사 추가, 바뀐 닉네임이 바로 화면에 적용되도록 함
- 닉네임에 대한 유효성검사 추가, 바뀐 닉네임 바로 url과 화면에 적용되도록 함
- window.location.replace -> useNavigate 사용하도록 변경

[Feat - front] 유효성검사추가 #122

---

back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.service.ts
back/server/src/chat/chat.service.ts
back/server/src/chat/chat.ts
back/server/src/game/game-manager.ts
back/server/src/game/game.service.ts
back/server/src/users/users.service.ts

-  채팅 모듈 리팩토링 및 버그 수정
-  로비에 사람이 없을때 로비 삭제하는 버그 수정
-  42 api uid, password 환경변수로 변경 (.env 슬랙 참조)
-  게임 생성 시 채팅방 연결 리팩토링

[Refact - Back] 채팅 모듈 리팩토링 및 버그 수정

---

back/server/src/users/users.service.ts

- 아바타 변경 시 이전 사진 삭제
- 아바타 변경 시 이전 사진 삭제하는 코드 구현

[Fix - Back] 아바타 변경 시 이전 사진 삭제 #143

---

front/client/package-lock.json
front/client/package.json
front/client/src/components/LoginChecker.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/modal/LogoutModal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/components/users/MatchTable.tsx
front/client/src/pages/Error.tsx
front/client/src/pages/Login.tsx
front/client/src/pages/SecondAuth.tsx
front/client/src/pages/Users.tsx
front/client/src/utils/axios.ts
front/client/src/utils/recoil/refresh.ts
front/client/src/utils/token.ts
front/client/yarn.lock

- 로그인 시 access, refresh Token 처리
- 토큰 및 갱신 처리
- 토큰 만료 시 로그아웃 처리

[Feat - Front] 액세스, 리프레시 토큰 처리

---

back/server/src/auth-jwt/auth-jwt.controller.ts
back/server/src/auth-jwt/auth-jwt.service.ts
back/server/src/auth-jwt/auth-jwt.stategyAccess.ts
back/server/src/auth-jwt/auth-jwt.stategyRefresh.ts
back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.service.ts
back/server/src/chat/chat.service.ts
back/server/src/game/game.service.ts

- jwt토큰 재발급 구현및 보완
- 만료된 jwt토큰 사용시 발생하는 에러 수정
- 리프래쉬 토큰 만료전 재발급 구현

[Fix-Back] 로그인 관련 버그수정 리프래시 토큰 발급#137

---

back/server/src/auth/auth.service.ts

-  토큰 못받는 버그 수정
- redirection 쿼리를 수정했습니다

[Fix-Back] 토큰 못받는 버그 수정

---

back/server/src/chat/chat.module.ts
back/server/src/chat/chat.service.ts

-  개인 차단 채팅메시지 처리 수정
- 개인 차단한 사람의 메시지 보이던 버그 수정

[Fix-Back] 개인 차단 채팅메시지 처리 수정 #152

---

back/server/src/auth/auth.service.ts
back/server/src/chat/chat.service.ts
back/server/src/users/dto/res-user-mypage.dto.ts
back/server/src/users/users.service.ts

-  프로필 친구 여부 데이터 보내기
- 프로필페이지 데이터 요청시 친구 여부 데이터 추가

[Feat - Back] 프로필 친구 여부 데이터 보내기 #155

---

back/server/.prettierrc

- 저장 시 tab indent가 4로 맞춰지도록 prettier 설정파일을 변경했습니다.

[Fix-Back] prettier tab indent 4로 변경

---

back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.service.ts
back/server/src/channel/dto/get-channelList.dto.ts
back/server/src/game/game-manager.ts
back/server/src/game/game.gateway.ts
back/server/src/game/game.module.ts
back/server/src/game/game.service.ts
back/server/src/game/game.ts
back/server/src/game/match-manager.ts
back/server/src/match/dto/create-match.dto.ts
back/server/src/users/users.service.ts

- 같이하기 기능 구현.
- 게임 종료 시 전적 DB에 기록하는 기능 구현.
- 몇 가지 에러가 남아있으나 daekim님, yongwkim님 작업에 필요한 부분이 있어서 미리 머지하겠습니다.

Feat back/게임 기능추가 및 리팩토링

---

front/client/src/components/layout/Side.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/pages/Game.tsx
front/client/src/types/myDataTypes.ts
front/client/src/types/userTypes.ts
front/client/src/utils/recoil/myData.ts

- 방장 기능 처리
- 음소거 시간 확인
- 오너, 어드민 분리

[Fix - Front] 방장 기능 처리

---

back/server/src/users/dto/create-user.dto.ts

-  닉네임 validation 수정
-  닉네임 validation 수정 - 영어 숫자만 가능, 최대 8글자

[Fix - Back] 닉네임 validation 수정

---

front/client/src/components/layout/UserList.tsx

- 최초 로그인 시 유저리스트 처리
- 최초 로그인 시 유저리스트 비어있는 현상 처리

[Fix - Front] 최초 로그인 시 유저리스트 처리

---

back/server/src/chat/chat.service.ts
back/server/src/friend/dto/res-friend.dto.ts
back/server/src/match/match.service.ts

-  친구목록에 유저 현재채널 추가
- 친구목록에 유저 현재채널 추가
- 경기기록 map에서 return 안해준 문제 해결

[Fix - Back] 친구목록에 유저 현재채널 추가 및 경기기록 dto 수정

---

front/client/src/components/game/GameModule.tsx
front/client/src/components/layout/Nav.tsx
front/client/src/components/modal/LogoutModal.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/users/FriendTable.tsx
front/client/src/components/users/MatchTable.tsx
front/client/src/components/users/UserInfo.tsx
front/client/src/styles/Lobby/Lobby.css
front/client/src/styles/game/Game.css
front/client/src/styles/layout/Nav.css
front/client/src/styles/layout/Side.css
front/client/src/styles/users/FriendList.css
front/client/src/styles/users/MatchList.css
front/client/src/styles/users/MyPage.css
front/client/src/styles/users/UserInfo.css
front/client/src/types/myDataTypes.ts
front/client/src/types/profileTypes.ts
front/client/src/utils/recoil/myData.ts

- 친구리스트에 같이하기/관전하기 추가, 2차인증 활성/비활성화 추가, CSS 일부 수정
- 친구리스트에 관전하기, 게임신청 기능 추가하기
- 2차인증 활성/비활성화 기능 추가
- 네비게이션 등 CSS 일부 수정

[Fix - Front] 친구리스트, 2차인증 기능추가

---

back/server/src/friend/entities/friend.entity.ts
back/server/src/match/entities/match.entity.ts
back/server/src/stats/entities/stat.entity.ts

- DB에서 users테이블의 row를 삭제할 일이 있을때,
relation으로 묶인 테이블들 때문에 삭제가 안되어 불편했던 점을 해결하기 위해
entity에 cascade설정을 넣었습니다. 
이 설정을 넣어주면 users테이블의 row를 삭제할 때 relation으로 묶인 테이블의 row도 같이 삭제됩니다.

[Fix - Back] entity에 cascade 설정 추가

---

back/server/src/auth-jwt/auth-jwt.stategyRefresh.ts
back/server/src/auth/auth.service.ts
back/server/src/chat/chat.gateway.ts
back/server/src/chat/chat.service.ts
back/server/src/users/dto/create-user.dto.ts
back/server/src/users/dto/res-user-navi.dto.ts
back/server/src/users/entities/user.entity.ts
back/server/src/users/users.controller.ts
back/server/src/users/users.service.ts

- 2차인증 enable/disable 구현
- 2차인증 enable/disable 구현

[Feat - Back] 2차인증 enable/disable 구현

---

front/client/src/components/game/GameModule.tsx
front/client/src/components/layout/ChatList.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/Side.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/lobby/ChannelList.tsx
front/client/src/components/lobby/ChannelListRow.tsx
front/client/src/components/modal/GameStartModal.tsx
front/client/src/components/modal/LogoutModal.tsx
front/client/src/components/modal/ModalProvider.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/modal/ProfileModal.tsx
front/client/src/components/rank/RankTable.tsx
front/client/src/components/users/MatchTable.tsx
front/client/src/components/users/UserInfo.tsx
front/client/src/pages/Error.tsx
front/client/src/pages/SecondAuth.tsx
front/client/src/pages/Users.tsx
front/client/src/styles/Lobby/Lobby.css
front/client/src/styles/layout/Nav.css
front/client/src/styles/layout/Side.css
front/client/src/styles/modal/Modal.css
front/client/src/styles/users/FriendList.css
front/client/src/styles/users/MatchList.css

- 테스트 하며 수정사항 반영, 아이맥에서 잘 보이도록 css 수정
- 테스트 하며 수정사항 반영(인원 없애기, 채팅창에서는 프로필 모달 안뜨도록 등)
- 아이맥에서 잘 보이도록 css 수정

[Fix - front] 테스트 수정사항 반영, CSS 아이맥에 맞춰 수정

---

back/server/src/auth/auth.controller.ts
back/server/src/auth/auth.service.ts
front/client/src/pages/Login.tsx

- 42 API 로그인을 하여야만 테스트가 가능한 것을 개선하기 위해 
테스트 계정으로 로그인 하는 기능을 구현하였습니다.
- 메인 페이지에서 `테스트 로그인` 버튼을 누르면 테스트 계정으로 로그인 가능합니다.
(테스트 계정 정보도 DB users 테이블에 저장되니 참고해주세요.)
- 메인 페이지에서 `테스트 로그인` 버튼을 누르면 oauth/test API 호출.
- 랜덤한 닉네임 + 더미 정보 생성하여 users DB에 저장.
- jwt 토큰 발급.

[Feat - Back] 테스트 계정 로그인 기능 구현

---

front/client/src/components/layout/ChatList.tsx
front/client/src/components/modal/GameInviteModal.tsx
front/client/src/components/modal/InviteAcceptModal.tsx
front/client/src/components/modal/ModalProvider.tsx
front/client/src/components/modal/PasswordSubmitModal.tsx
front/client/src/components/users/FriendTable.tsx
front/client/src/components/users/MatchTable.tsx
front/client/src/pages/Game.tsx
front/client/src/styles/layout/Side.css

- 테스트 하며 아래와 같은 버그 해결함
- 비밀번호 방 입장 불가 해결
- 관리자 권한 위임 시 채팅방 초기화 해결
- 닉네임 변경 시 친구 목록이 깜박이는 현상 해결
- 플레이어 두 명 나갈 시 방이 사라짐 해결

[Fix - Front] 테스트 및 버그 수정

---

back/server/src/app.module.ts

- .env 경로 변경
- .env 경로 root로 변경

[Refact -  Back] .env 경로 변경

---

back/server/src/game/game-manager.ts
back/server/src/game/game.gateway.ts
back/server/src/game/game.service.ts
back/server/src/main.ts
back/server/src/users/users.service.ts

-  일부 버그 수정
-  채널 비밀번호 변경 시 채널 리스트 업데이트
-  서버 재실행 시 모든 유저 status, channel_id 초기화

[Fix - Back] 일부 버그 수정

---

front/client/package-lock.json
front/client/src/components/game/GameModule.tsx
front/client/src/components/layout/Layout.tsx
front/client/src/components/layout/UserList.tsx
front/client/src/components/modal/GameInviteModal.tsx
front/client/src/components/modal/InviteAcceptModal.tsx
front/client/src/components/modal/ModalProvider.tsx
front/client/src/components/modal/NickChangeModal.tsx
front/client/src/components/users/FriendTable.tsx
front/client/src/pages/Game.tsx
front/client/src/styles/Lobby/Lobby.css
front/client/src/styles/game/Game.css
front/client/src/styles/layout/Content.css
front/client/src/styles/layout/Nav.css
front/client/src/styles/layout/Side.css
front/client/src/styles/rank/Rank.css
front/client/yarn.lock

- 테스트 하며 아래와 같은 버그를 찾아냄 및 해결
- 비밀번호 방 입장 불가
- 관리자 권한 위임 시 채팅방 초기화
- 닉네임 변경 시 친구 목록이 깜박이는 현상
- 플레이어 두 명 나갈 시 방이 사라짐
- 접속 안 한 사람도 online으로 뜨는 현상 8/24
- 게임 중에 스크롤 생기는 현상(아이맥에서 확인 바람)8/24
- 최초 입장 시 유저리스트 안 보이는 현상 8/24
- 비밀번호 설정/해제 시 채널 리스트에 실시간 반영이 안됨 8/24
- 관전이 안됨 8/24
- 게임 플레이 멈추는 현상(async await으로 해결) 8/24
- 게임중 새로고침으로 나갈시 에러발생 8/24
- gamestart-regist 후 새로고침시 에러발생 8/24
- 2차인증 항상 하기가 늘 켜져있는 문제 8/24
- 유저리스트에 유저가 중복으로 추가되는 문제 8/24
- 닉네임을 바꾸면 친구목록이 깜빡거리는 현상 8/24
- 새로고침하면 유저가 2명이 된다! 8/25
- 초대했을 때 거절당해도 대기가 큐에서 사라지지 않음 8/25
- 초대 받았을 때 모달 바깥을 눌렀을 때는 정상적으로 거절이 되지 않음 8/25

[Fix - front] 테스트 및 버그 수정 ~220825

---

back/server/src/app.module.ts
back/server/src/users/users.service.ts

-  정적 파일 경로 ip 변경
-  정적 파일 경로 ip 변경

[Fix -  Back] 정적 파일 경로 ip 변경

---

back/server/src/main.ts
init.sh

[Feat - Back] HTTPS 통신 구현

---

front/client/src/components/layout/Nav.tsx
front/client/src/styles/index/index.css
front/client/src/styles/layout/Nav.css
front/client/src/styles/login/login.module.css
front/client/src/styles/rank/Rank.css
front/client/src/styles/users/MatchList.css

- 
- nav 버튼 이미지를, 텍스트 형태로 변경하였습니다.

Fix-Front/디자인변경레이아웃nav

---

front/client/src/components/layout/Nav.tsx
front/client/src/styles/layout/Nav.css

- 
- nav css 수정 (float 에서 flex로 수정)

[Fix - Front] 네비게이션 float에서 flex로 변경

---

front/client/src/components/lobby/ChannelListRow.tsx
front/client/src/pages/Lobby.tsx
front/client/src/styles/Lobby/Lobby.css

Fix-Front/loby디자인수정

---

front/client/src/components/rank/RankRow.tsx
front/client/src/components/rank/RankTitleRow.tsx
front/client/src/styles/Lobby/Lobby.css
front/client/src/styles/index/index.css
front/client/src/styles/layout/Frame.css
front/client/src/styles/rank/Rank.css
front/client/src/styles/users/MyPage.css

- [Fix-Front] Rank디자인수정
- 타이틀 디자인수정
- 랭킹 리스트 디자인수정

[Fix-Front] Rank디자인수정

---

front/client/src/App.tsx
front/client/src/styles/modal/Modal.css

[Fix - front] 모달 디자인 변경
